### ISSUE TITLE
Abort because of huge memory allocation

### ISSUE THREAD

**Issue by patataofcourse** [SolraBizna/loop-ogg#1]
```
$ loop-ogg /tmp/a.ogg
memory allocation of 16363776000 bytes failed
Aborted (core dumped)
```
I used latest commit at time of writing
Here's the file that caused this error, it's just a beat track exported w/ audacity
[a.ogg.zip](https://github.com/SolraBizna/loop-ogg/files/10193814/a.ogg.zip)

**Comment by SolraBizna** [comment]
This is happening because the `LOOP_START` and `LOOP_END` metadata are expected to contain seconds, but in that file they contain sample numbers. `loop-ogg` is trying to allocate enough memory for a 36-hour loop.

Change the metadata to either:

```
LOOP_START=4.0049375
LOOP_END=8
```

or:

```
LOOPSTART=128158
LOOPLENGTH=127842
```

and this should solve the problem.

It's a little strange that the readme doesn't explain the metadata *at all*, so I'm going to add that missing information.

Edit: I think I'll also add a case to detect when `LOOP_START` and `LOOP_END` are specified in samples. If they're both integers, and both much larger than the length of the track in seconds, it should be safe to consider them sample numbers.

**Comment by patataofcourse** [comment]
okay, thank you!

**Comment by SolraBizna** [comment]
By the way, it seems that the loop point was also slightly off. Here is the same Ogg, but with the loop start adjusted to be exactly 4 seconds.

[a.ogg.zip](https://github.com/SolraBizna/loop-ogg/files/10196686/a.ogg.zip)

**Comment by SolraBizna** [comment]
f0374e9 should play your original file just fine, albeit with a slight click due to the choice of loop point, and a couple of warnings. The new readme should also resolve any confusion as to how the metadata works. I will leave it to you to close this issue if resolved.

Thank you for the issue report, and especially for including a sample file. :)

**Comment by patataofcourse** [comment]
no worries! i know how unhelpful a vague issue can be
